#! /bin/sh

host=$(hostname -s)
if ! pgrep sxhkd > /dev/null; then
    sxhkd -m -1 &
fi

if [ $host = "galatea" ]; then
    bar="desktop-bar"
    feh --bg-fill Imágenes/thewitness.png

    if ! pgrep picom > /dev/null; then
	picom -b --config ~/.config/picom.conf
    fi

    if ! pgrep redshift-gtk > /dev/null; then
	redshift-gtk &
    fi

elif [ $host = "proteus" ]; then
    bar="notebook-bar"
    if ! pgrep blueman-applet > /dev/null; then
        blueman-applet &
    fi
    if ! pgrep optimus-manager-qt > /dev/null; then
        optimus-manager-qt &
    fi
    feh --bg-fill Images/thewitness.png
    if ! pgrep picom > /dev/null; then
	picom -b --config ~/.config/picom-notebook.conf
    fi

    if ! pgrep clight > /dev/null; then
	clight &
    fi

fi

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload $bar &
done

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 10
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Emacs state=tiled
