#! /bin/sh

host=$(hostname -s)
if ! pgrep compton > /dev/null; then
    compton --config ~/.config/compton.conf &
fi
if ! pgrep sxhkd > /dev/null; then
    sxhkd -m -1 &
fi
if [ $host = "proteus" ]; then
  polybar notebook-bar &
elif [ $host = "galatea" ]; then
  for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload desktop-bar &
  done 
fi

feh --randomize --bg-fill ~/Imágenes/wallpapers/ultrawide/low-contrast &

if ! pgrep redshift > /dev/null; then
    redshift &
fi

if ! pgrep mpd > /dev/null; then
    mpd .config/mpd/mpd.conf &
fi

.config/lock/lock.sh

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 10
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
